#!/usr/bin/env bash
# =============================================================
# Section 2: Configure Host Network on Sensor LAN
#
# Brings the host's sensor-side NIC online with the static IP
# defined in config/network_config.yaml (default: 192.168.1.5),
# detects whether the NIC supports IEEE 1588 hardware
# timestamping, and verifies the path to the RUTM50 router.
#
# This script does NOT configure the RUTM50 / PoE switch
# itself — those are web-UI steps and are documented in the
# README §2 (Reference Network Configuration). What this
# script does is the matching host-side change so the rest of
# the pipeline can talk to the sensor LAN.
#
# Position in the sequence:
#   ./1_install_packages.sh
#   ./2_configure_host_network.sh    ← you are here
#   ./3_setup_ins_to_pc_sync.sh
#   ./4_setup_lidar_ptp.sh
#   ./5_setup_camera_ptp.sh
#
# What it does:
#   1. Reads ETH_IFACE + HOST_IP from network_config.yaml
#   2. Brings the interface up with HOST_IP/24
#   3. Detects HW vs SW PTP timestamping via ethtool -T
#   4. Pings the RUTM50 router (gateway) as a sanity check
#   5. Exports a marker file /run/hitch_dome_net.env that
#      script #3 reads to pick HW vs SW ptp4l mode
#
# The ip-addr-add is non-persistent. For a permanent assignment,
# add the same IP via netplan or NetworkManager (the README §2
# shows both).
#
# Usage:
#   chmod +x 2_configure_host_network.sh
#   ./2_configure_host_network.sh
#   ./2_configure_host_network.sh --eth enp0s31f6 --host-ip 192.168.1.5
# =============================================================

set -euo pipefail

# ─── Load defaults from /config/network_config.yaml ──────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../config/load_network_config.sh
source "$SCRIPT_DIR/../config/load_network_config.sh"

# ─── Configuration (env > CLI > YAML) ────────────────────────
ETH_IFACE="${ETH_IFACE:-$NETCFG_ETH}"
HOST_IP="${HOST_IP:-$NETCFG_HOST_IP}"
ROUTER_IP="${ROUTER_IP:-$NETCFG_ROUTER_IP}"
ADD_ALIAS=0

# ─── Parse arguments ─────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --eth)               ETH_IFACE="$2"; shift 2 ;;
        --eth=*)             ETH_IFACE="${1#*=}"; shift ;;
        --host-ip)           HOST_IP="$2"; shift 2 ;;
        --host-ip=*)         HOST_IP="${1#*=}"; shift ;;
        --add-factory-alias) ADD_ALIAS=1; shift ;;
        *)                   echo "Unknown arg: $1"; exit 1 ;;
    esac
done

# ─── Helpers ─────────────────────────────────────────────────
info()  { echo -e "\n\033[1;34m[INFO]\033[0m $*"; }
warn()  { echo -e "\n\033[1;33m[WARN]\033[0m $*"; }
ok()    { echo -e "\033[1;32m[ OK ]\033[0m $*"; }
fail()  { echo -e "\033[1;31m[FAIL]\033[0m $*"; exit 1; }

# =============================================================
info "Section 2: Configure host network"
info "  Ethernet: $ETH_IFACE"
info "  Host IP:  $HOST_IP/24"
info "  Router:   $ROUTER_IP"
echo ""

# ─── 1. Validate interface ──────────────────────────────────
if ! ip link show "$ETH_IFACE" &>/dev/null; then
    fail "Interface $ETH_IFACE not found. Available: $(ip -br link show | awk '{print $1}' | tr '\n' ' ')"
fi

# ─── 2. Bring up + assign IP ────────────────────────────────
info "Bringing $ETH_IFACE up with $HOST_IP/24..."
sudo ip link set "$ETH_IFACE" up
sudo ip addr add "$HOST_IP/24" dev "$ETH_IFACE" 2>/dev/null || \
    warn "  $HOST_IP already assigned to $ETH_IFACE (continuing)"
ok "$ETH_IFACE up with $HOST_IP/24"

# ─── 3. Detect hardware timestamping ────────────────────────
info "Probing PTP timestamping capability via ethtool..."
if ethtool -T "$ETH_IFACE" 2>/dev/null | grep -q "hardware-transmit"; then
    ok "Hardware timestamping supported on $ETH_IFACE (sub-µs PTP achievable)"
    PTP_TIMESTAMPING="hardware"
else
    warn "No hardware timestamping — software mode (20–50 µs PTP accuracy)"
    PTP_TIMESTAMPING="software"
fi

# Persist the choice so script 3 can pick it up
sudo tee /run/hitch_dome_net.env > /dev/null << EOF
# Auto-generated by 2_configure_host_network.sh — consumed by 3_setup_ins_to_pc_sync.sh
ETH_IFACE=$ETH_IFACE
HOST_IP=$HOST_IP
PTP_TIMESTAMPING=$PTP_TIMESTAMPING
EOF
ok "Saved /run/hitch_dome_net.env for script 3"

# ─── 4. Optional: temporary 172.168.1.100/24 alias ──────────
# Robin W ships at the factory IP 172.168.1.10 (per User Manual V2.2 §3.1)
# which is not in the project's 192.168.1.0/24. The provisioning script
# (./provision_robin_w_multiunit.sh) needs a host route into 172.168.1.0/24
# during its run; it adds and removes the alias automatically. We do NOT
# add it here unless --add-factory-alias is passed.
if [ "$ADD_ALIAS" = "1" ]; then
    info "Adding temporary 172.168.1.100/24 alias for factory-IP LiDAR access..."
    sudo ip addr add 172.168.1.100/24 dev "$ETH_IFACE" 2>/dev/null || \
        warn "  Alias already present"
    ok "Factory-IP alias up — ping 172.168.1.10 to test"
fi

# =============================================================
# Self-test
# =============================================================
verify_network() {
    local PASS=0 FAIL=0 WARN_COUNT=0
    echo ""
    echo "============================================================="
    echo " VERIFICATION: Section 2 — Host network"
    echo "============================================================="

    info "Test 1/4: $ETH_IFACE link state"
    if ip link show "$ETH_IFACE" 2>/dev/null | grep -q "state UP"; then
        ok "  $ETH_IFACE is UP"
        PASS=$((PASS+1))
    else
        warn "  $ETH_IFACE link is DOWN — cable / RUTM50 port?"
        WARN_COUNT=$((WARN_COUNT+1))
    fi

    info "Test 2/4: $HOST_IP assigned"
    if ip -4 -o addr show dev "$ETH_IFACE" | grep -q "$HOST_IP/24"; then
        ok "  $HOST_IP/24 present on $ETH_IFACE"
        PASS=$((PASS+1))
    else
        echo "  FAIL: $HOST_IP/24 not present on $ETH_IFACE"
        FAIL=$((FAIL+1))
    fi

    info "Test 3/4: PTP timestamping mode"
    ok "  Mode = $PTP_TIMESTAMPING (written to /run/hitch_dome_net.env)"
    PASS=$((PASS+1))

    info "Test 4/4: RUTM50 router reachable at $ROUTER_IP"
    if ping -c 2 -W 2 "$ROUTER_IP" &>/dev/null; then
        ok "  $ROUTER_IP responds to ping"
        PASS=$((PASS+1))
    else
        warn "  $ROUTER_IP did not respond — check RUTM50 power / port / WAN-as-LAN config"
        WARN_COUNT=$((WARN_COUNT+1))
    fi

    echo ""
    echo "============================================================="
    echo " RESULTS: $PASS passed, $WARN_COUNT warnings, $FAIL failed"
    echo "============================================================="
    echo ""
    echo " Next: ./3_setup_ins_to_pc_sync.sh"
    echo ""
}

verify_network
